### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by GordonGuenther** [dockerized-php/phpmd#1]
When using dockerizedphp/phpmd I often run into memory problems.
E.g. "PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 10489856 bytes) in phar:///usr/bin/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Util/Cache/Driver/FileCacheDriver.php on line 151" or
"PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in phar:///usr/bin/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Util/Cache/Driver/FileCacheDriver.php on line 201"

Could you please provide an environment variable (for example called PHP_MEMORY_LIMIT) for your docker container I can set on the docker run in order to inject a higher memory limit to the PHP process within the Docker container?

Running without memory limit could than look like:
docker run -e PHP_MEMORY_LIMIT='-1' -v `pwd`:/app dockerizedphp/phpmd src html unusedcode

**Comment by tommy-muehle** [comment]
Hi @GordonGuenther,

I hope it's not too late! You can easily set such an option when you override the entrypoint to PHP, set the relevant INI value and then call phpmd. For example:
```
docker run --rm -ti -v $(PWD):/app --entrypoint=php dockerizedphp/phpmd -dmemory_limit=-1 /usr/bin/phpmd
```

So you can avoid the additional environment variable. And sorry for the late answer!

Best,
Tommy
